// This canister is a thin wrapper around the `ic-vetkeys` EncryptedMaps
// library. The canister owns the single MemoryManager and hands EncryptedMaps
// the four Memory instances it needs; the `#[init]`/`#[post_upgrade]` and every
// `#[query]`/`#[update]` endpoint are generated by the library macro, which
// guarantees the exposed Candid matches what the `@icp-sdk/vetkeys` frontend
// expects.
use ic_stable_structures::memory_manager::{MemoryId, MemoryManager, VirtualMemory};
use ic_stable_structures::DefaultMemoryImpl;
use std::cell::RefCell;

type Memory = VirtualMemory<DefaultMemoryImpl>;

thread_local! {
    static MEMORY_MANAGER: RefCell<MemoryManager<DefaultMemoryImpl>> =
        RefCell::new(MemoryManager::init(DefaultMemoryImpl::default()));
}

fn memory(id: u8) -> Memory {
    MEMORY_MANAGER.with(|m| m.borrow().get(MemoryId::new(id)))
}

// The first argument is the domain-separator string that isolates this
// application's derived keys; it must stay stable for the life of the canister.
// The four Memory instances back EncryptedMaps' own stable state, in the order
// it expects: config (which persists the domain separator and vetKD key id),
// access control, shared keys, and the encrypted values.
ic_vetkeys::export_encrypted_maps_canister!(
    "password_manager_app",
    [memory(0), memory(1), memory(2), memory(3)],
);

ic_cdk::export_candid!();
