[package]
name = "x509_example_rust"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
candid = "=0.10.4"
der = { version = "0.7.9", features = ["alloc", "derive", "flagset", "oid"] }
ecdsa = { version = "0.16.9", features = ["alloc", "pkcs8", "pem"] }
ed25519 = { version = "2.2.3", features = ["alloc", "pkcs8", "pem"] }
ed25519-dalek = { version = "2.1.1" }
elliptic-curve = { version = "0.13.8", features = ["pkcs8"] }
getrandom = { version = "0.2", features = ["custom"] }
hex = "0.4"
ic-cdk = "0.16"
k256 = "0.13.3"
pkcs8 = "0.10.2"
sha2 = "0.10"
serde = "1.0"
serde_bytes = "0.11"
signature = "2.2.0"
spki = "0.7.3"
strum = "0.26.3"
strum_macros = "0.26.3"
x509-cert = { version = "0.2.5", features = ["builder"] }

[dev-dependencies]
openssl = "0.10.66"
pocket-ic = "5.0.0"
