import { defineConfig } from "vite";
import { readFileSync } from "fs";
import { execSync } from "child_process";
import { icpBindgen } from "@icp-sdk/bindgen/plugins/vite";

function getDevServerConfig() {
  // Try icp-cli first
  try {
    const canisterId = execSync("icp canister status backend -e local -i", {
      encoding: "utf-8",
      stdio: "pipe",
    }).trim();
    const networkStatus = JSON.parse(
      execSync("icp network status --json", {
        encoding: "utf-8",
        stdio: "pipe",
      })
    );
    return {
      headers: {
        "Set-Cookie": `ic_env=${encodeURIComponent(
          `ic_root_key=${networkStatus.root_key}&PUBLIC_CANISTER_ID:backend=${canisterId}`
        )}; SameSite=Lax;`,
      },
      proxy: {
        "/api": { target: "http://127.0.0.1:8000", changeOrigin: true },
      },
    };
  } catch {}

  // Try dfx
  try {
    execSync("dfx ping", { encoding: "utf-8", stdio: "pipe" });
    return {
      proxy: {
        "/api": {
          target: "http://127.0.0.1:4943",
          changeOrigin: true,
        },
      },
      host: "127.0.0.1",
    };
  } catch {}

  throw new Error(
    "No local network running. Start with:\n  icp network start -d && icp deploy\nor:\n  dfx start --background && dfx deploy"
  );
}

export default defineConfig(({ command }) => {
  // Load .env file (generated by dfx) if it exists
  try {
    const envFile = readFileSync("../.env", "utf-8");
    for (const line of envFile.split("\n")) {
      const match = line.match(/^([A-Z_]+[A-Z0-9_]*)=(.+)$/);
      if (match) process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, "");
    }
  } catch {}

  return {
    base: "./",
    plugins: [
      icpBindgen({
        didFile: "../backend/backend.did",
        outDir: "./src/bindings",
      }),
    ],
    define: { "process.env": process.env },
    optimizeDeps: {
      esbuildOptions: { define: { global: "globalThis" } },
    },
    server: command === "serve" ? getDevServerConfig() : undefined,
  };
});
