[package]
name = "ic-fun-with-guards"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.15"
scopeguard = "1.2.0"
serde = "1.0"

[dev-dependencies]
assert_matches = "1.5.0"
pocket-ic = "4.0.0"
