[package]
edition = "2021"
name = "backend"
version = "1.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
candid = "0.10"
colorgrad = "0.6"
ic-cdk = "0.12"
bytes = "1.5.0"
prost = "0.11.0"
prost-types = "0.11.0"
image = { version = "0.24", features = ["png"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
tract-onnx = { git = "https://github.com/sonos/tract", version = "=0.21.2-pre" }
ic-stable-structures = "0.6"
ic-wasi-polyfill = { git = "https://github.com/wasm-forge/ic-wasi-polyfill", version = "0.3.17" }
