[toolchain]
moc = "1.14.1"

[dependencies]
core = "2.6.1"
bitcoin = "0.2.0"
ic = "4.0.0"

[moc]
args = [ "--default-persistent-actors", "-W=M0236,M0237,M0223" ]

[canisters.backend]
main = "backend/main.mo"
