[package]
name = "defi_dapp"
version = "0.1.0"
edition = "2018"

## See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.13"
ic-cdk = "0.18.0"
ic-ledger-types = "0.15.0"
num-bigint = "0.4"
num-traits = "0.2"
serde = "1.0.219"

[dev-dependencies]
tempfile = "3.2.0"
