[toolchain]
moc = "1.14.1"

[dependencies]
core = "2.6.1"

[moc]
args = [ "--default-persistent-actors", "-W=M0236,M0237,M0223" ]

[canisters.caller]
main = "caller/main.mo"
args = [ "--default-persistent-actors", "-W=M0236,M0237,M0223", "--actor-env-alias", "callee", "PUBLIC_CANISTER_ID:callee", "callee/callee.did" ]

[canisters.callee]
main = "callee/main.mo"
candid = "callee/callee.did"
