[package]
name = "low_wasm_memory_hook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk-macros = "0.18.0-alpha.1"
ic-cdk = "0.18.0-alpha.1"
serde = "1.0.171"
serde_bytes = "0.11"
serde_json = "1.0.94"
