[toolchain]
moc = "1.14.1"

[dependencies]
core = "2.6.1"

[moc]
args = [ "--default-persistent-actors", "-W=M0236,M0237,M0223" ]

[canisters.backend]
main = "backend/main.mo"
candid = "backend/backend.did"
args = [ "--default-persistent-actors", "-W=M0236,M0237,M0223", "--actor-env-alias", "icrc1_ledger", "PUBLIC_CANISTER_ID:icrc1_ledger", "candid/icrc1_ledger.did" ]
