= DFINITY Apps in C =

DFINITY uses standard wasm binaries, so we may use standard tools such as Clang
to build apps.

# Running in Docker

To create a docker container with all the libraries required and `dfx`, follow the below instructions.  If you already have a debian environment you'd like to use, skip to the following section.

 Create a docker file with the below text:
 
  FROM debian
  RUN apt-get update
  RUN apt-get install -y curl gnupg xz-utils wget git
  RUN apt install -y lsb-release wget software-properties-common
  RUN bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  CMD ["/bin/bash"]
  WORKDIR /usr/src
 
Create the new docker container by running the following command 

  $ docker build --tag debian:dfx .

Start the instance with 

  $ docker run -ti --name dfx debian:dfx
  
This will launch you into your instance. Now we need to pull the code by running:

  $ cd usr/src
  $ git clone https://github.com/dfinity/examples.git
  
Install the DFINITY Canister SDK using

  $ sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
  
# Compiling the C code  

If you are not using the docker container you need to install Clang:

RUN bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

and set up a couple of aliases. Navigate to the `examples/c/reverse` directory. Set up the following aliases:

``` sh
  $ alias wld="wasm-ld-11 --no-entry --export-dynamic --allow-undefined"
  $ alias wcc="clang-11 --target=wasm32 -c -O3"
```
  
Note that the version of the compiler that you may need to use in these aliases may change.  You can look in usr/bin to see what version was installed on your instance.

== Reverse a string ==

The file `reverse.c` contains function that reverses a string in place. Build a
wasm binary with:

  $ wcc reverse.c
  $ wld reverse.o -o reverse.wasm

Now we need to build the dfx package.  The dfx.json and reverse.did that you need are provided in this repo.  Much of this is usually taken care of when you issue a dfx new command.

  $ dfx canister create reverse
  
You now need a seperate terminal (docker exec -ti dfx bash) to start the dfx server. Make sure you are in the reverse directory and run

  $ dfx start
  
Now install the cannister

  $ dfx canister install --all
  
Now you can call your reverse function!

  $ dfx canister call reverse go '("test")'

The script `build.sh` performs the above steps.

Ignoring the error message about "cannot find method type, dfx will send message with inferred type", we see:

  ("tset")
