[toolchain]
moc = "1.14.1"

[dependencies]
core = "2.6.1"
hex = "1.0.3"

[moc]
args = [ "--default-persistent-actors", "-W=M0236,M0237,M0223", "--actor-id-alias", "icp_ledger", "ryjl3-tyaaa-aaaaa-aaaba-cai", "candid/icp_ledger.did" ]

[canisters.backend]
main = "backend/main.mo"
