/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChargeRouteImport } from './routes/charge'
import { Route as IndexRouteImport } from './routes/index'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargeRoute = ChargeRouteImport.update({
  id: '/charge',
  path: '/charge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charge': typeof ChargeRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charge': typeof ChargeRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charge': typeof ChargeRoute
  '/config': typeof ConfigRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/setup': typeof SetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charge'
    | '/config'
    | '/history'
    | '/login'
    | '/receive'
    | '/send'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charge'
    | '/config'
    | '/history'
    | '/login'
    | '/receive'
    | '/send'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/charge'
    | '/config'
    | '/history'
    | '/login'
    | '/receive'
    | '/send'
    | '/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChargeRoute: typeof ChargeRoute
  ConfigRoute: typeof ConfigRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charge': {
      id: '/charge'
      path: '/charge'
      fullPath: '/charge'
      preLoaderRoute: typeof ChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChargeRoute: ChargeRoute,
  ConfigRoute: ConfigRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
