[package]
name = "hello_canister"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
ic-cdk = "0.18.7"
ic-cdk-macros = "0.18.7"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }
ic-stable-structures = "0.6.1"
async-trait = "0.1"

[dev-dependencies]
pocket-ic = "9.0.2"
candid = "0.10"
tokio = { version = "1.0", features = ["macros", "rt"] }
walkdir = "2.0"
