name: backend_wasm64
on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/backend_wasm64/**
      - .github/workflows/backend_wasm64.yml
      - .github/workflows/_run-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-backend_wasm64:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/backend_wasm64
      run: |
        icp network start -d
        icp deploy
        bash test.sh
