name: backend_only

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/backend_only/**
      - rust/backend_only/**
      - .github/workflows/backend_only.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-backend_only:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/backend_only
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-backend_only:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/backend_only
      run: |
        icp network start -d
        icp deploy
        bash test.sh
