name: basic_ethereum

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/basic_ethereum/**
      - .github/workflows/basic_ethereum.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-basic_ethereum:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/basic_ethereum
      run: |
        icp network start -d
        icp deploy
        bash test.sh
