name: canister-info

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/canister-info/**
      - .github/workflows/canister-info.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-canister-info:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/canister-info
      run: |
        icp network start -d
        icp deploy
        bash test.sh
