name: cert-var

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/cert-var/**
      - .github/workflows/cert-var.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-cert-var:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/cert-var
      run: |
        icp network start -d
        icp deploy
        bash test.sh
