name: composite_query

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/composite_query/**
      - rust/composite_query/**
      - .github/workflows/composite_query.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-composite_query:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy and test
        working-directory: motoko/composite_query
        run: |
          icp network start -d
          icp deploy --cycles 30t
          bash test.sh

  rust-composite_query:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy and test
        working-directory: rust/composite_query
        run: |
          icp network start -d
          icp deploy --cycles 30t
          bash test.sh
