name: composite_query

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/composite_query/**
      - rust/composite_query/**
      - .github/workflows/composite_query.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-composite_query:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/composite_query
      run: |
        icp network start -d
        icp deploy --cycles 30t
        bash test.sh

  rust-composite_query:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/composite_query
      run: |
        icp network start -d
        icp deploy --cycles 30t
        bash test.sh
