name: daily_planner

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/daily_planner/**
      - rust/daily_planner/**
      - .github/workflows/daily_planner.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-daily_planner:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/daily_planner
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-daily_planner:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/daily_planner
      run: |
        icp network start -d
        icp deploy
        bash test.sh
