name: encrypted-notes-example
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-encrypted-notes-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Encrypted Notes Example Darwin (unit tests)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-unit BUILD_ENV=motoko MATCHERS="$(dfx cache show)/motoko-matchers/src"
          popd
      - name: Motoko Encrypted Notes Example Darwin (e2e)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-e2e BUILD_ENV=motoko
          popd
  motoko-encrypted-notes-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Encrypted Notes Example Linux (unit tests)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-unit BUILD_ENV=motoko MATCHERS="$(dfx cache show)/motoko-matchers/src"
          popd
      - name: Motoko Encrypted Notes Example Linux (e2e)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-e2e BUILD_ENV=motoko
          popd
  rust-encrypted-notes-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Rust Encrypted Notes Example Darwin (unit tests)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-unit BUILD_ENV=rust
          popd
      - name: Rust Encrypted Notes Example Darwin (e2e)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-e2e BUILD_ENV=rust
          popd
  rust-encrypted-notes-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Rust Encrypted Notes Example Linux (unit tests)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-unit BUILD_ENV=rust
          popd
      - name: Rust Encrypted Notes Example Linux (e2e)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-e2e BUILD_ENV=rust
          popd
