name: evm_block_explorer

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/evm_block_explorer/**
      - rust/evm_block_explorer/**
      - .github/workflows/evm_block_explorer.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-evm_block_explorer:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/evm_block_explorer
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-evm_block_explorer:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/evm_block_explorer
      run: |
        icp network start -d
        icp deploy
        bash test.sh
