name: face-recognition

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/face-recognition/**
      - .github/workflows/face-recognition.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-face-recognition:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/face-recognition
      run: |
        apt-get update && apt-get install -y --no-install-recommends build-essential
        icp network start -d
        icp deploy
        bash test.sh
