name: filevault

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/filevault/**
      - .github/workflows/filevault.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-filevault:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/filevault
      run: |
        icp network start -d
        icp deploy
        bash test.sh
