name: flying_ninja

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/flying_ninja/**
      - rust/flying_ninja/**
      - .github/workflows/flying_ninja.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-flying_ninja:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/flying_ninja
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-flying_ninja:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/flying_ninja
      run: |
        icp network start -d
        icp deploy
        bash test.sh
