name: guards

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/guards/**
      - .github/workflows/guards.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-guards:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/guards
      run: |
        icp network start -d
        icp deploy
        bash test.sh
        cargo build --package backend --target wasm32-unknown-unknown --release
        cargo test --package backend
      install-pocketic: true
      pocketic-version: "14.0.0"
