name: hello_cycles

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/hello_cycles/**
      - .github/workflows/hello_cycles.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-hello_cycles:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/hello_cycles
      run: |
        icp network start -d
        icp deploy
        bash test.sh
