name: hello-example
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-hello-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Hello Example Darwin
        run: |
          dfx start --background
          pushd motoko/hello
          make test
          popd
  motoko-hello-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Hello Example Linux
        run: |
          dfx start --background
          pushd motoko/hello
          make test
          popd
  rust-hello-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Install Rust Darwin
        run: bash .github/workflows/install-rust-darwin.sh
      - name: Rust Hello Example Darwin
        run: |
          dfx start --background
          pushd rust/hello
          make test
          popd
  rust-hello-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Install Rust Linux
        run: bash .github/workflows/install-rust-linux.sh
      - name: Rust Hello Example Linux
        run: |
          dfx start --background
          pushd rust/hello
          make test
          popd
