name: hello_world

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/hello_world/**
      - rust/hello_world/**
      - .github/workflows/hello_world.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/hello_world
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/hello_world
      run: |
        icp network start -d
        icp deploy
        bash test.sh
