name: hosting-photo-storage

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - hosting/photo-storage/**
      - .github/workflows/hosting-photo-storage-example.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hosting-photo-storage:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: all
      working-directory: hosting/photo-storage
      run: |
        icp network start -d
        icp deploy
