name: hosting-static-website
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - hosting/static-website/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/hosting-static-website-example.yaml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  hosting-unity-static-website-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Hosting Static Website Darwin
        run: |
          dfx start --background
          pushd hosting/static-website
          dfx deploy
          popd
  hosting-static-website-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Hosting Static Website Linux
        run: |
          dfx start --background
          pushd hosting/static-website
          dfx deploy
          popd
