name: hosting-photo-storage

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - hosting/photo-storage/**
      - .github/workflows/hosting-photo-storage-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hosting-photo-storage:
    runs-on: ubuntu-24.04
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install dependencies
        run: npm install -g @icp-sdk/icp-cli @icp-sdk/ic-wasm ic-mops
      - name: Deploy
        working-directory: hosting/photo-storage
        run: |
          icp network start -d
          icp deploy
