name: ic_pos

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/ic-pos/**
      - .github/workflows/ic_pos.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-ic_pos:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy and test
        working-directory: motoko/ic-pos
        run: |
          icp network start -d
          bash deploy.sh
          bash test.sh
