name: icp_transfer

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/icp_transfer/**
      - rust/icp_transfer/**
      - .github/workflows/icp_transfer.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-icp_transfer:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/icp_transfer
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-icp_transfer:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/icp_transfer
      run: |
        icp network start -d
        icp deploy
        bash test.sh
