name: icrc2-swap

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/icrc2-swap/**
      - .github/workflows/icrc2-swap.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-icrc2-swap:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/icrc2-swap
      run: |
        icp network start -d
        bash deploy.sh
        bash test.sh
