name: inter-canister-calls

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/inter-canister-calls/**
      - .github/workflows/inter-canister-calls.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-inter-canister-calls:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/inter-canister-calls
      run: |
        icp network start -d
        icp deploy
        bash test.sh
