name: llm_chatbot

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/llm_chatbot/**
      - rust/llm_chatbot/**
      - .github/workflows/llm_chatbot.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-llm_chatbot:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/llm_chatbot
      run: |
        icp network start -d
        icp deploy

  rust-llm_chatbot:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/llm_chatbot
      run: |
        icp network start -d
        icp deploy
