name: motoko-defi
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/defi/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-defi-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-defi-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Defi Darwin
        run: |
          pushd motoko/defi
          bash ./scripts/install.sh
          bash ./test/demo.sh
          bash ./test/trade.sh
          bash ./test/transfer.sh
          popd
  motoko-defi-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Defi Linux
        run: |
          pushd motoko/defi
          bash ./scripts/install.sh
          bash ./test/demo.sh
          bash ./test/trade.sh
          bash ./test/transfer.sh
          popd
