name: motoko-pub-sub
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/pub-sub/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-pub-sub-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-pub-sub-example-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Pub-Sub Darwin
        run: |
          dfx start --background
          pushd motoko/pub-sub
          make test
          popd
  motoko-pub-sub-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Pub-Sub Linux
        run: |
          dfx start --background
          pushd motoko/pub-sub
          make test
          popd
