name: motoko-ios-notifications
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/ios-notifications/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/ios-notifications-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-ios-notifications-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko iOS Notifications Darwin
        run: |
          pushd motoko/ios-notifications/dapp-demo
          make test
          popd
  motoko-ios-notifications-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko iOS Notifications Linux
        run: |
          pushd motoko/ios-notifications/dapp-demo
          make test
          popd
