name: motoko-random_maze
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/random_maze/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-random_maze-example.yaml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-random_maze-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Random Maze Darwin
        run: |
          dfx start --background
          pushd motoko/random_maze
          make test
          popd
  motoko-random_maze-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Random Maze Linux
        run: |
          dfx start --background
          pushd motoko/random_maze
          make test
          popd
