name: motoko-cert-var
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/cert-var/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-cert_var-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-cert-var-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Certified Variable Darwin
        run: |
          dfx start --background
          pushd motoko/cert-var
          make test
          popd
  motoko-cert-var-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Certified Variable Linux
        run: |
          dfx start --background
          pushd motoko/cert-var
          make test
          popd
