# Known failure: https://dfinity.atlassian.net/browse/EM-5
name: motoko-token_transfer_from
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/token_transfer_from/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-token-transfer-from-example.yml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-token_transfer_from-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Ledger Transfer Darwin
        run: |
          pushd motoko/token_transfer_from
          bash ./demo.sh
          popd
  motoko-token_transfer_from-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Ledger Transfer Linux
        run: |
          pushd motoko/token_transfer_from
          bash ./demo.sh
          popd
