name: motoko-dip721
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/dip721-nft-container/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-dip721-example.yml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-dip721-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko DIP-721 Darwin
        run: |
          pushd motoko/dip721-nft-container
          bash ./demo.sh
          popd
  motoko-dip721-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko DIP-721 Linux
        run: |
          pushd motoko/dip721-nft-container
          bash ./demo.sh
          popd
