name: motoko-persistent-storage
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/persistent-storage/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-persistent-storage-example.yaml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-persistent-storage-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Persistent Storage Darwin
        run: |
          dfx start --background
          pushd motoko/persistent-storage
          make test
          popd
  motoko-persistent-storage-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Persistent Storage Linux
        run: |
          dfx start --background
          pushd motoko/persistent-storage
          make test
          popd
