name: motoko-threshold-schnorr
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/threshold-schnorr/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-threshold-schnorr-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-threshold-schnorr-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Threshold Schnorr Darwin
        run: |
          dfxvm default 0.22.0-beta.0
          dfx start --background
          npm install @noble/curves
          pushd motoko/threshold-schnorr
          make test
  motoko-threshold-schnorr-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Threshold Schnorr Linux
        run: |
          dfxvm default 0.22.0-beta.0
          dfx start --background
          npm install @noble/curves
          pushd motoko/threshold-schnorr
          make test
