name: oisy_signer_demo
on:
  push:
    branches: [master]
  pull_request:
    paths:
      - hosting/oisy-signer-demo/**
      - .github/workflows/oisy_signer_demo.yml
      - .github/workflows/_run-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  oisy_signer_demo:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: all
      working-directory: hosting/oisy-signer-demo
      run: |
        icp network start -d
        icp deploy
