name: parallel_calls

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/parallel_calls/**
      - rust/parallel_calls/**
      - .github/workflows/parallel_calls.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-parallel_calls:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/parallel_calls
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  motoko-parallel_calls-multi-subnet:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: all
      working-directory: motoko/parallel_calls
      run: |
        bash test-multi-subnet.sh

  rust-parallel_calls:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/parallel_calls
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-parallel_calls-multi-subnet:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/parallel_calls
      run: |
        bash test-multi-subnet.sh
      install-pocketic: true
