name: performance_counters

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/performance_counters/**
      - .github/workflows/performance_counters.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-performance_counters:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/performance_counters
      run: |
        icp network start -d
        icp deploy
        bash test.sh
