name: periodic_tasks

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/periodic_tasks/**
      - .github/workflows/periodic_tasks.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-periodic_tasks:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/periodic_tasks
      run: |
        icp network start -d
        icp deploy
        bash test.sh
