name: photo_gallery

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/photo_gallery/**
      - .github/workflows/photo_gallery.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-photo_gallery:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/photo_gallery
      run: |
        icp network start -d
        icp deploy
        bash test.sh
