name: pub-sub

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/pub-sub/**
      - .github/workflows/pub-sub.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-pub-sub:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/pub-sub
      run: |
        icp network start -d
        icp deploy
        bash test.sh
