name: qrcode

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/qrcode/**
      - .github/workflows/qrcode.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-qrcode:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/qrcode
      run: |
        icp network start -d
        icp deploy
        bash test.sh
