name: query_stats

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/query_stats/**
      - rust/query_stats/**
      - .github/workflows/query_stats.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-query_stats:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy and test
        working-directory: motoko/query_stats
        run: |
          icp network start -d
          icp deploy
          bash test.sh

  rust-query_stats:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy and test
        working-directory: rust/query_stats
        run: |
          icp network start -d
          icp deploy
          bash test.sh
