name: query_stats

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/query_stats/**
      - rust/query_stats/**
      - .github/workflows/query_stats.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-query_stats:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/query_stats
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-query_stats:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/query_stats
      run: |
        icp network start -d
        icp deploy
        bash test.sh
