name: random_maze

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/random_maze/**
      - .github/workflows/random_maze.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-random_maze:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/random_maze
      run: |
        icp network start -d
        icp deploy
        bash test.sh
