name: receiving_icp

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/receiving-icp/**
      - .github/workflows/receiving-icp.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-receiving_icp:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/receiving-icp
      run: |
        icp network start -d
        icp deploy
        bash test.sh
