name: rust-minimal-counter-dapp-example
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rust-minimal-counter-dapp-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Install Rust Darwin
        run: bash .github/workflows/install-rust-darwin.sh
      - name: Rust Minimal Counter Dapp Example Darwin
        run: |
          dfx start --background
          pushd rust/minimal-counter-dapp
          make test
          popd
  rust-minimal-counter-dapp-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Install Rust Linux
        run: bash .github/workflows/install-rust-linux.sh
      - name: Rust Minimal Counter Dapp Example Linux
        run: |
          dfx start --background
          pushd rust/minimal-counter-dapp
          make test
          popd
