# Known failure: https://dfinity.atlassian.net/browse/EM-5
name: rust-icp_transfer
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/icp_transfer/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-icp-transfer-example.yml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-icp_transfer-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Rust Tokens Transfer Darwin
        run: |
          pushd rust/icp_transfer
          bash ./demo.sh
          popd
  rust-icp_transfer-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Rust Tokens Transfer Linux
        run: |
          pushd rust/icp_transfer
          bash ./demo.sh
          popd
