name: rust-canister-info
on:
  pull_request:
    paths-ignore:
      - rust/canister-info/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-canister-info-example.yml
      - .github/workflows/rust-canister-info-skip.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
