name: rust-vetkeys-password-manager-with-metadata
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/vetkeys/password_manager_with_metadata/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/password-manager-with-metadata-example.yml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  password-manager-with-metadata-rust-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Pre-download network launcher
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/workflows/pre-download-launcher.sh
      - name: Rust vetkeys password-manager-with-metadata Rust Darwin
        run: |
          pushd rust/vetkeys/password_manager_with_metadata/rust
          icp network start -d
          icp deploy
          popd
  password-manager-with-metadata-rust-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Pre-download network launcher
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/workflows/pre-download-launcher.sh
      - name: Rust vetkeys password-manager-with-metadata Rust Linux
        run: |
          pushd rust/vetkeys/password_manager_with_metadata/rust
          icp network start -d
          icp deploy
          popd
  password-manager-with-metadata-motoko-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Pre-download network launcher
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/workflows/pre-download-launcher.sh
      - name: Rust vetkeys password-manager-with-metadata Motoko Darwin
        run: |
          pushd rust/vetkeys/password_manager_with_metadata/motoko
          icp network start -d
          icp deploy
          popd
  password-manager-with-metadata-motoko-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Pre-download network launcher
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/workflows/pre-download-launcher.sh
      - name: Rust vetkeys password-manager-with-metadata Motoko Linux
        run: |
          pushd rust/vetkeys/password_manager_with_metadata/motoko
          icp network start -d
          icp deploy
          popd
