name: rust-vetkeys-basic-ibe

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/vetkeys/basic_ibe/**
      - .github/workflows/rust-vetkeys-basic-ibe-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-basic-ibe:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:0.1.0
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Basic Ibe Rust
        working-directory: rust/vetkeys/basic_ibe/rust
        run: icp network start -d && icp deploy
  motoko-basic-ibe:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:0.1.0
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Basic Ibe Motoko
        working-directory: rust/vetkeys/basic_ibe/motoko
        run: icp network start -d && icp deploy
