name: send_http_post

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/send_http_post/**
      - rust/send_http_post/**
      - .github/workflows/send_http_post.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-send_http_post:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/send_http_post
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-send_http_post:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/send_http_post
      run: |
        icp network start -d
        icp deploy
        bash test.sh
