name: simd

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/simd/**
      - .github/workflows/simd.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-simd:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/simd
      run: |
        icp network start -d
        icp deploy
        bash test.sh
