name: svelte-motoko-starter
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  svelte-motoko-starter-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Svelte Motoko Starter Example Darwin
        run: |
          dfx start --background
          pushd svelte-motoko-starter
          make test
          popd
  svelte-motoko-starter-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Svelte Motoko Starter Example Linux
        run: |
          dfx start --background
          pushd svelte-motoko-starter
          make test
          popd
