name: threshold-schnorr

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/threshold-schnorr/**
      - rust/threshold-schnorr/**
      - .github/workflows/threshold-schnorr.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-threshold-schnorr:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy and test
        working-directory: motoko/threshold-schnorr
        run: |
          icp network start -d
          icp deploy
          bash test.sh

  rust-threshold-schnorr:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Build WASM
        working-directory: rust/threshold-schnorr
        run: icp build backend
      - name: Install PocketIC server
        uses: dfinity/pocketic@a980c334fab1b21b0b8a6bba38e1a10836e7258b # main
        with:
          pocket-ic-server-version: "15.0.0"
      - name: Run PocketIC integration tests
        working-directory: rust/threshold-schnorr
        run: cargo test --package backend --test integration_tests
      - name: Deploy and test
        working-directory: rust/threshold-schnorr
        run: |
          icp network start -d
          icp deploy
          bash test.sh
