name: threshold-schnorr

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - motoko/threshold-schnorr/**
      - rust/threshold-schnorr/**
      - .github/workflows/threshold-schnorr.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko-threshold-schnorr:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/threshold-schnorr
      run: |
        icp network start -d
        icp deploy
        bash test.sh

  rust-threshold-schnorr:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/threshold-schnorr
      run: |
        apt-get update && apt-get install -y --no-install-recommends clang
        icp build backend
        cargo test --package backend --test integration_tests
        icp network start -d
        icp deploy
        bash test.sh
      install-pocketic: true
