name: unity_ii_deeplink

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - native-apps/unity_ii_deeplink/**
      - .github/workflows/unity_ii_deeplink.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  native-apps-unity_ii_deeplink:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: native-apps/unity_ii_deeplink
      run: |
        icp network start -d
        icp deploy
        bash test.sh
