name: vetkeys-encrypted-notes-app-vetkd

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/vetkeys/encrypted_notes_app_vetkd/**
      - rust/vetkeys/encrypted_notes_app_vetkd/**
      - .github/workflows/vetkeys-encrypted-notes-app-vetkd.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/vetkeys/encrypted_notes_app_vetkd
      run: |
        icp network start -d
        icp deploy

  rust:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/vetkeys/encrypted_notes_app_vetkd
      run: |
        icp network start -d
        icp deploy
