name: vetkeys-password-manager

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/vetkeys/password_manager/**
      - .github/workflows/vetkeys-password-manager.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:0.1.0
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Password Manager Rust
        working-directory: rust/vetkeys/password_manager/rust
        run: icp network start -d && icp deploy
  motoko:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:0.1.0
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Password Manager Motoko
        working-directory: rust/vetkeys/password_manager/motoko/backend
        run: icp network start -d && icp deploy
