name: vetkeys-basic-ibe

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/vetkeys/basic_ibe/**
      - rust/vetkeys/basic_ibe/**
      - .github/workflows/vetkeys-basic-ibe.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: motoko/vetkeys/basic_ibe
      run: |
        icp network start -d
        icp deploy

  rust:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/vetkeys/basic_ibe
      run: |
        icp network start -d
        icp deploy
