name: vetkeys-password-manager-with-metadata

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/vetkeys/password_manager_with_metadata/**
      - .github/workflows/vetkeys-password-manager-with-metadata.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/vetkeys/password_manager_with_metadata/rust
      run: |
        icp network start -d && icp deploy

  motoko:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: motoko
      working-directory: rust/vetkeys/password_manager_with_metadata/motoko
      run: |
        icp network start -d && icp deploy
