name: vetkeys-basic-bls-signing

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/vetkeys/basic_bls_signing/**
      - rust/vetkeys/basic_bls_signing/**
      - .github/workflows/vetkeys-basic-bls-signing.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  motoko:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy
        working-directory: motoko/vetkeys/basic_bls_signing
        run: |
          icp network start -d
          icp deploy

  rust:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy
        working-directory: rust/vetkeys/basic_bls_signing
        run: |
          icp network start -d
          icp deploy
