name: vetkeys-basic-timelock-ibe

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/vetkeys/basic_timelock_ibe/**
      - .github/workflows/vetkeys-basic-timelock-ibe.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/vetkeys/basic_timelock_ibe
      run: |
        icp network start -d && icp deploy
