name: vetkeys-basic-ibe

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/vetkeys/basic_ibe/**
      - .github/workflows/vetkeys-basic-ibe.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:0.3.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Basic Ibe Rust
        working-directory: rust/vetkeys/basic_ibe/rust
        run: icp network start -d && icp deploy
  motoko:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:0.3.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Basic Ibe Motoko
        working-directory: rust/vetkeys/basic_ibe/motoko
        run: icp network start -d && icp deploy
