name: vetkeys-password-manager-with-metadata

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/vetkeys/password_manager_with_metadata/**
      - .github/workflows/vetkeys-password-manager-with-metadata.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:0.1.0
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Password Manager With Metadata Rust
        working-directory: rust/vetkeys/password_manager_with_metadata/rust
        run: icp network start -d && icp deploy
  motoko:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:0.1.0
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Password Manager With Metadata Motoko
        working-directory: rust/vetkeys/password_manager_with_metadata/motoko
        run: icp network start -d && icp deploy
