name: rust-vetkeys-basic-bls-signing

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/vetkeys/basic_bls_signing/**
      - .github/workflows/vetkeys-basic-bls-signing.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-basic-bls-signing:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-rust:0.1.0
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Basic Bls Signing Rust
        working-directory: rust/vetkeys/basic_bls_signing/rust
        run: icp network start -d && icp deploy
  motoko-basic-bls-signing:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:0.1.0
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Deploy Basic Bls Signing Motoko
        working-directory: rust/vetkeys/basic_bls_signing/motoko
        run: icp network start -d && icp deploy
