name: wasm_counter

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - wasm/counter/**
      - .github/workflows/wasm_counter.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wasm-counter:
    runs-on: ubuntu-24.04
    container: ghcr.io/dfinity/icp-dev-env-motoko:1.0.1
    env:
      ICP_CLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install wabt
        run: apt-get install -y wabt
      - name: Deploy and test
        working-directory: wasm/counter
        run: |
          icp network start -d
          icp deploy
          bash test.sh
