name: wasm_counter

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - wasm/counter/**
      - .github/workflows/wasm_counter.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wasm-counter:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: all
      working-directory: wasm/counter
      run: |
        apt-get update && apt-get install -y wabt
        icp network start -d
        icp deploy
        bash test.sh
