name: x509

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - rust/x509/**
      - .github/workflows/x509.yml
      - .github/workflows/_run-example.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-x509:
    uses: ./.github/workflows/_run-example.yml
    with:
      language: rust
      working-directory: rust/x509
      run: |
        apt-get update && apt-get install -y --no-install-recommends libssl-dev pkg-config
        icp build backend
        cargo test --package backend --test integration_tests
        icp network start -d
        icp deploy
        bash test.sh
      install-pocketic: true
